### ISSUE TITLE
Ajouter Matrix (Element) dans les messageries

### ISSUE THREAD

**Issue by Angedestenebres** [YannJaulin/protege-moi-sur-internet#1]
Bonjour,

Je pense que le titre parle de lui-même ^^

- Site du projet Matrix : https://matrix.org/
- Client Element (le plus populaire) : https://element.io/

Et au besoin, un peu de doc en Français : https://tedomum.net/service/matrix/

**Comment by YannJaulin** [comment]
Bonjour Angedestenebres !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Je connais très bien le logiciel Element et son protocole Matrix, j'ai l'intention de l'ajouter ^^

Je vois que le Pull Request #3 a été ouvert, je vais regarder ça, merci Fanch :slightly_smiling_face:
