### ISSUE TITLE
Proposition : ajout de Delta Chat dans la liste des outils de messagerie

### ISSUE THREAD

**Issue by mathieumatiu** [YannJaulin/protege-moi-sur-internet#11]
bonjour
Je propose d'ajouter Delta Chat dans la liste des outils de messagerie.
Delta Chat est un logiciel de messagerie sécurisé de type chat, ne nécessitant aucun compte d'inscription, aucun serveur central, aucune donnée personnelle échangée, aucun accès extérieur au carnet d'adresse.
La messagerie est utilisable avec n'importe qui à partir du moment ou on connaît son adresse e-mail, et les échanges sont automatiquement chiffrés avec Autocrypt.
 
vous pouvez consulter les détails ici : https://delta.chat/fr/help

**Comment by YannJaulin** [comment]
Bonjour mathieumatiu !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Après renseignement sur l'application de messagerie Delta Chat, il ne remplit malheureusement pas les conditions requises pour être ajouté dans la liste des messageries conseillées :confused:

Bien qu'il n'ait aucun serveur central et qu'il soit chiffré, il présente des problèmes de sécurité telle que les fuites de métadonnées, comme indiqué [ici](https://github.com/privacytools/privacytools.io/issues/859).

Désolé et encore merci pour la suggestion :slightly_smiling_face:
