### ISSUE TITLE
proposition Ajout email ik.me

### ISSUE THREAD

**Issue by Moubai** [YannJaulin/protege-moi-sur-internet#12]
proposition d'ajouter de ik.me la nouvelle messagerie gratuite de chez infomaniak
https://www.infomaniak.com/fr/email-gratuit

**Comment by YannJaulin** [comment]
Bonjour Moubai !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Je connais le service de courrier Infomaniak, j'ai l'intention de l'ajouter ^^

Je fais la présentation et je le mets en ligne sur le site dans les jours qui suivent :eyes:

Encore merci et à dans quelques jours :slightly_smiling_face:

**Comment by MickGe** [comment]
Bonjour,

Je proposerais également [mailo.com](https://www.mailo.com) !

**Comment by YannJaulin** [comment]
Bonsoir MickGe !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Après renseignement sur le service de courrier Mailo, il ne remplit malheureusement pas les conditions requises pour être ajouté dans la liste des services de courrier conseillées :confused:

Bien qu'il soit éthique et qu'il respecte la vie privée, il affiche des bannières publicitaires dans le type de compte gratuit et des cookies peuvent être déposés sur le navigateur par des régies publicitaires afin de les personnaliser, comme indiqué sur la page [Règles de confidentialité](https://www.mailo.com/mailo/fr/regles-de-confidentialite.php).

Désolé et encore merci pour la suggestion :slightly_smiling_face:
