### ISSUE TITLE
Ajouter lilo dans la liste des moteurs de recherche

### ISSUE THREAD

**Issue by Angedestenebres** [YannJaulin/protege-moi-sur-internet#2]
Tout est dans le titre :)

Site : https://www.lilo.org/
Page Wikipedia : https://fr.wikipedia.org/wiki/Lilo_(entreprise)

**Comment by YannJaulin** [comment]
Bonjour Angedestenebres !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Je vais me renseigner sur Lilo, je reviens vers vous dès que j'ai de plus ample information :eyes:

**Comment by bristow** [comment]
Lilo est un méta moteur (tout comme ecosia), je ne recommande pas.

**Comment by Angedestenebres** [comment]
Bien que je comprenne le point de vue, en soi, si on part ce principe, on peut enlever quasi tous ceux listés actuellement.

Reste à savoir si on veut lister des moteurs de recherche uniquement ou des outils qui n'en sont pas forcément mais qui protègent la vie privée. SeaX qui est listé, bien que libre, n'est qu'un métamoteur aussi par exemple.

Maintenant si lilo n'est pas retenu, c'est pas bien grave, ça reste une propostion parmi tant d'autres :wink:

**Comment by YannJaulin** [comment]
Bonsoir @Angedestenebres et @bristow !

Après renseignement sur le moteur de recherche Lilo, il ne remplit malheureusement pas les conditions requises pour être ajouté dans la liste des moteurs de recherche conseillées :confused: 

Bien qu'il soit éthique et qu'il ne collecte aucune donnée, il utilise des algorithmes de recherche tiers (Google, Yahoo, Bing) et ils peuvent collecter des données et placer des cookies publicitaires, comme indiqué sur la page [privacy](https://www.lilo.org/privacy/).

Désolé et encore merci pour la suggestion :slightly_smiling_face:
