### ISSUE TITLE
Incohérence à propos de Telegram

### ISSUE THREAD

**Issue by supermamie** [YannJaulin/protege-moi-sur-internet#4]
Dans la liste des messageries, il n'y a pas Telegram, cependant il est dans la liste des moyens de contacts (contrairement aux autres messageries de la liste)
C'est un peu incohérent non ?

**Comment by FanchTheSystem** [comment]
Salut, 

Le serveur coté Telegram n'est pas libre, du coup il y a pas vraiment moyen de savoir si ils protègent la vie privée ou pas.

Donc ça peux être un moyen de contact pour l'auteur du site, mais a mon avis, ça ne devrait pas être dans la liste des messageries conseillées

**Comment by supermamie** [comment]
je n'utilise pas Telegram pour cette raison justement, mais du coup, il serait peut être mieux que le contact puisse se faire sur quelquechose que l'on peut conseiller.
Sinon ça donne vraiment l'impression que ce qui est sécurisé est moins bien que le reste ve que c'est autre chose qui est utilisé par le créateur du site.

**Comment by YannJaulin** [comment]
Bonjour supermamie !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Effectivement, Telegram n'est pas Open Source, c'est donc pour cela que je ne le conseille pas dans la liste des messageries ^^

Mais, comme l'a dit Fanch, merci pour sa participation d'ailleurs, c'est un moyen de contact que j'utilise pour le site.

La raison est qu'il me permet de plus facilement répondre aux messages et de faire des annonces, car tout comme Twitter, que je ne conseille pas non plus, c'est un service populaire et utilisé par beaucoup de personnes, il me permet de rendre le site plus visible.

Je suis d'accord sur le fait que c'est mieux d'utiliser un service conseillé pour me contacter, je le fais déjà avec ProtonMail et Mastodon que je vais bientôt conseiller sur le site, mais certains services comportent des limites pour la communication, c'est donc pour cela que j'utilise Telegram.

Ayant déjà beaucoup de personnes qui m'ont contacté dessus, je préfère le garder dans la liste des moyens de contact, mais l'idée de souligner que ce n'est pas un service qui est conseillé est intéressante, il y a des modifications à faire !

Merci beaucoup pour l'idée :slightly_smiling_face:

**Comment by supermamie** [comment]
Il y a visiblement bientôt Matrix qui va arriver dans la liste d'outils conseillés, ça sera parfait pour de la messagerie instantanée :)

**Comment by YannJaulin** [comment]
Effectivement, c'est une possibilité :slightly_smiling_face:
