### ISSUE TITLE
Startpage n'est plus recommendable 

### ISSUE THREAD

**Issue by StereotypicalGeek** [YannJaulin/protege-moi-sur-internet#5]
Startpage a été racheté par une société qui publicitaire nommée System1 (source : [https://www.ghacks.net/2019/11/16/startpage-search-owner-changes-raise-serious-questions/](url) ) Il n'y a pas de preuves qu'ils se soient mis à collecter des données sur les utilisateurs mais ce genre de comportement est très suspect.

Je recommanderais plutôt [https://swisscows.com](url) qui est un moteur de recherche Suisse à la place de Startpage.

**Comment by YannJaulin** [comment]
Bonjour StereotypicalGeek !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Je suis au courant pour le rachat de Startpage par la société publicitaire System1, mais si je l'ai gardé sur le site, c'est pour sa transparence.

En effet, Startpage a partagé beaucoup d'information sur leur fonctionnement et ce qui a changé depuis leur rachat.

De ce que j'en ai retenu, il reste très sérieux sur la protection de la vie privée.

C'est donc pour cela que je préfère le garder dans la liste des moteurs de recherche conseillées.

Pour en savoir plus, voici [un lien](https://github.com/privacytools/privacytools.io/issues/1562) qui regroupe tout ce qui a été dit sur Startpage :slightly_smiling_face:

Concernant Swisscows, je vais me renseigner, je reviens vers vous dès que j'ai de plus ample information :eyes:

**Comment by YannJaulin** [comment]
Bonsoir @StereotypicalGeek !

Après renseignement sur le moteur de recherche Swisscows, il a l'air de remplir les conditions requises pour être ajouté dans la liste des moteurs de recherche conseillées :partying_face: 

Merci d'ouvrir une nouvelle issue, afin que je puisse commencer sa présentation :slightly_smiling_face: 

Merci d'avance !
