### ISSUE TITLE
Correction homepage FR de Protonmail

### ISSUE THREAD

**Issue by the-hornet-and-the-bumblebee** [YannJaulin/protege-moi-sur-internet#6]
Hello,
Sur la page de présentation de ProtonMail, le lien vers la page d'accueil française est https://protonmail.com/fr/ (et non https://protonmail.com/default/fr/ qui renvoie un 404).

**Comment by YannJaulin** [comment]
Bonjour the-hornet-and-the-bumblebee !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

C'est exact, le lien redirige vers une page d'erreur, il a été changé.

Je vais le corriger, encore merci de m'avoir prévenu ^^

Je vois que le Pull Request #8 a été ouvert, je vais regarder ça, merci MickaelAz :slightly_smiling_face:
