### ISSUE TITLE
Proposition d'ajout posteo.de dans la liste des courriels

### ISSUE THREAD

**Issue by nmereaux** [YannJaulin/protege-moi-sur-internet#7]
Proposition d'ajout
[Posteo](https://posteo.de/fr) est un service de messagerie open source, respectueux de la vie privée.

**Comment by YannJaulin** [comment]
Bonjour nmereaux !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Je connais le service de courrier Posteo, j'ai l'intention de l'ajouter ^^

Je fais la présentation et je le mets en ligne sur le site dans les jours qui suivent :eyes: 

Encore merci et à dans quelques jours :slightly_smiling_face:
