### ISSUE TITLE
Quelques idées à trier

### ISSUE THREAD

**Issue by FanchTheSystem** [YannJaulin/protege-moi-sur-internet#9]
Salut,

Il y a probablement des idées de logiciel à piquer sur cette page:
https://entraide.chatons.org/fr/

Tous ne sont peut-être pas des projets assez "mure" pour le site, mais je crois que çà reste intéressant comme source d'inspiration.

Et du coup ça me fait penser, que peut-être ça serait intéressant, de trouver un moyen simple de parler des CHATONS sur le site. Parce que beaucoup d'entre eux propose des outils qui collent parfaitement avec l'objectif du site.

(Je peux éventuellement en proposer quelqu'un en pull request, il suffit de demander ;) )

**Comment by tifriis208** [comment]
De même, merci pour ce beau projet ! Je pense qu'il pourrait s'inspirer des propositions faites sur ce site : https://www.privacytools.io/

D'ailleurs, ce site a aussi été traduit en français (pour info : https://privacytools.dreads-unlock.fr/)

**Comment by YannJaulin** [comment]
Bonjour FanchTheSystem !

Merci beaucoup pour votre contribution à l'annuaire, cela aide grandement à son évolution :blush:

Encore merci pour les idées de logiciel, il y en a quelques-uns qui seront ajoutés sur le site (PrivateBin, Ethercalc, Etherpad...), c'est une très bonne source d'inspiration :grin:

Je suis totalement d'accord sur ta proposition, @FanchTheSystem, comme les CHATONS sont français et proposent des services libres, il serait intéressant de mettre un lien vers les CHATONS sur les pages où ils proposent le même service (Jitsi Meet, par exemple), ça permettra de parler des CHATONS :slightly_smiling_face: 

Je suis intéressé pour les Pull Request, encore merci :smile: 

- - -

De rien, @tifriis208, ça me fait vraiment plaisir que cela te plaît :blush: 

Je connais très bien PrivacyTools, je m'en sers beaucoup pour analyser les logiciels/services proposés, c'est vraiment un super site, encore merci pour la source :slightly_smiling_face:
